[package]
name = "ssccs_poc"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-clone = "1"
blake3 = "1.5"
hex = "0.4.3"
serde = { version = "1", features = ["derive"] }
bincode = "1"
thiserror = "1"
